// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbseikboavxzuqwvmjwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impic2Vpa2JvYXZ4enVxd3ZtandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTA0MzMsImV4cCI6MjA1OTE2NjQzM30.wc2HaBTmwJFPWnJtCndZg37JgHVu8p-h6aZ-m5v8KzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);